export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_PROFILE_RECEIVE = "USER_PROFILE_RECEIVE";
export const USER_SET_ID = "USER_SET_ID";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
